'use strict';
var express = require('express');
var app = express();
var bodyParser = require('body-parser');
var authorize = require('./src/authorize/auth');
var apis = require('./src/routes/api');
var pages = require('./src/routes/pages');
var errors = require('./src/routes/errors');
var log = require('./src/helpers/log');
var file = require('./src/api/file');
var multer = require('multer');
var storage = file.config();
var upload = multer({ storage: storage });
var cookieParser = require('cookie-parser');
global.appRoot = __dirname;
app.set('port', (process.env.PORT || 8000));
app.set('views', __dirname + '/src/static/views');
app.set('view engine', 'ejs');
app.engine('html', require('ejs').renderFile);
app.use('/libs', express.static(__dirname + '/node_modules'));
app.use('/css', express.static(__dirname + '/src/static/css'));
app.use('/js', express.static(__dirname + '/src/static/js'));
app.use('/img', express.static(__dirname + '/src/static/img'));
app.use('/files', express.static(__dirname + '/files'));
app.use('/favicon.ico', express.static(__dirname + '/src/static/img/favicon.ico'));
app.use('/fonts', express.static(__dirname + '/src/static/fonts'));
app.use('/resources', express.static(__dirname + '/src/static/resources'));
app.use('/backend', express.static(__dirname + '/src/static/views/backend'));
app.use('/partials', express.static(__dirname + '/src/static/views/partials'));
app.use('/static', express.static(__dirname + '/src/static/views/static'));
app.use(cookieParser());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true, limit: '10mb' }));
app.get('/google45b207d384e8d6ea.html', function (req, res) {
    res.status(200).render('pages/google45b207d384e8d6ea.html');
})
app.post('/api/v1/files', authorize.protectPath, upload.single('file'), function (req, res) { file.upload(file, req, res) });
app.use('/api/v1/', apis);
app.use('/', pages);
app.use(errors);
app.listen(app.get('port'), function () {
    log.write('App is running on port ' + app.get('port'));
});
